### ISSUE TITLE
Design schema for members

### ISSUE THREAD

**Issue by eyhhuang** [TechPlus-UW/techplusuw-api#17]
Since Tech+ members are likely to have multiple roles or "graduate" to new roles fairly recently, it doesn't necessarily make sense to have completely separate schemas for mentors, mentees, coffee chat mentors, etc. So, we should think carefully about our schema design(s).

One option is to have a single table that stores every single member and every type of information. This feels like more like a data dump than a structured database. This can also reduce performance.
However, this lets us get a snapshot of each member's current info and history with Tech+ more easily. To get the complete data for a member, regardless of the fact that they were a mentee in F19, Mentor and Coffee Chattor in F20, etc. would require a single query as opposed to queries and joins from multiple tables.

Another option is to have a one table that stores the admin info of each member, e.g. name, email, and other tables specifically for mentors, mentees, coffee-chats etc. If a member is a mentor and a coffee chat member, then they will have a row in the respective tables. This allows a Tech+ initiative, like mentorship, to see all the members in their initiatve in a single query. This also allows us to have tables to store relationships, e.g. mentor-mentee pairs, without having duplicated info (i.e. the mentor stores their mentee in one row and the mentee stores their mentor in another row).

**Comment by mahadzaryab1** [comment]
@eyhhuang I see that you mentioned tables in both options - does that mean we're shifting to SQL rather than NoSQL? Or will we have data in both places and use them accordingly?

**Comment by eyhhuang** [comment]
> @eyhhuang I see that you mentioned tables in both options - does that mean we're shifting to SQL rather than NoSQL? Or will we have data in both places and use them accordingly?

Thanks for pointing that out! Technically the first option where we have a single "table", we'll have a single nosql db and every member's will have a json document that stores all their info

**Comment by eyhhuang** [comment]
Finalized db schema for members! Check the notion at Tools -> Tools team page -> central portal -> db schema proposal
