### ISSUE TITLE
Add database migrations to application

### ISSUE THREAD

**Issue by mahadzaryab1** [TechPlus-UW/techplusuw-api#35]
Flask-Migrate allows database migrations based on the model changes between the existing database and the current data models. Implement this library in the application so that we don't need to drop the table and recreate it every time there is a change in the data model. The documentation can be found [here](https://flask-migrate.readthedocs.io/en/latest/).

**Comment by noredeen-alzubi** [comment]
I'm seeing that mentees and mentors have a `term` field but members also have a `term_level`. Are they the same thing? If so, I can remove the column from the child models and put it in the member table instead.

**Comment by mahadzaryab1** [comment]
> @mahadzaryab1 I'm seeing that mentees and mentors have a `term` field but members also have a `term_level`. Are they the same thing? If so, I can remove the column from the child models and put it in the member table instead.

They're not the same thing - `term_level` is supposed to hold the members' term like 2A, 3B, etc, whereas `term` is supposed to contain term specific information used in matching. As of right now, I don't see a use for `term` so you can go ahead and remove it.

**Comment by noredeen-alzubi** [comment]
Sounds good.
